# @package _global_

# Be careful when using _raw, history
obs:
  obs_dict:
    actor_obs: ???
    critic_obs: ???

  history_length:
    actor_obs: ???
    critic_obs: ???

  obs_scales: ???

  noise_scales: ???

  obs_dims: ???
  # Will store values after preprocessing, don't put anything here
  post_compute_config: {} 
