# @package _global_

domain_rand:
  # push robots
  push_robots : False
  push_interval_s : [5, 16]
  max_push_vel_xy : 1.0

  # base com
  randomize_base_com : False
  base_com_range:
    x : [-0.01, 0.01]
    y : [-0.01, 0.01]
    z : [-0.01, 0.01]

  # link mass
  randomize_link_mass : True
  link_mass_range : [0.9, 1.2]

  # pd gain
  randomize_pd_gain : True
  kp_range : [0.9, 1.1]
  kd_range : [0.9, 1.1]

  # friction
  randomize_friction : True
  friction_range : [0.5, 1.25] # [0.1, 1.0]

  # base mass
  randomize_base_mass : True
  added_mass_range : [-1., 3.]

  # rfi
  randomize_torque_rfi : False
  rfi_lim : 0.1
  randomize_rfi_lim : False
  rfi_lim_range : [0.5, 1.5]


  # control delay
  randomize_ctrl_delay : True
  lower_body_ctrl_delay: True
  upper_body_ctrl_delay: True
  ctrl_delay_step_range : [0, 1] # integer max real delay is 90ms